export const DEV_SESSION = {
  authToken: "Baerer TestTokenKey",
  userId: "6109ff5ba798542bfb2771ec",
};

export const DEV_USER = {
  id: "6109ff5ba798542bfb2771ec",
  nombre: "Test User",
  usuario: "TestUser",
  fechaCreacion: "2021-07-09T19:48:18.824Z",
  fechaActualizacion: "2021-08-09T19:29:58.838Z",
  correo: "test.user@belray.cl",
  faenas: ["Faena Test", "Faena Test 2", "Faena Test 3"],
  plataformas: {
    planning: {
      autorizacion: true,
      actProgRegistrosLista: {
        title: [],
        subtitle: [],
        content: [],
        footer: [],
      },
      rol: "Administrador",
      ordenColumnas: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
      visibilidadColumnas: [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
      ],
      confirmacionActividad: false,
    },
    vales: { autorizacion: true, rol: "Administrador" },
    tribolab: { autorizacion: true, rol: "Administrador" },
    biblioteca: { autorizacion: true, rol: "Administrador" },
    dashboard: { autorizacion: true, rol: "Administrador" },
    dashreport: { autorizacion: true, rol: "Administrador" },
    platform: { autorizacion: true, rol: "Administrador" },
  },
  cargo: "Testing User",
  habilitado: true,
};
